[general]
	#The Application ID of the Discord App to use. Replace this with your client id from the discord dashboard to change the name of the app
	applicationID = 1136518862070894633
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 18

[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "%player% заправляет дирижабль"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://www.dropbox.com/scl/fi/tjpu26x8qecq8fxdj5s0f/_-_-_.png?rlkey=okrdw69upjrdnmd10iune8igq&dl=1"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Майнкрафт Сборка [%mcver%]"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["https://www.dropbox.com/scl/fi/3yytv5pmonpds8sba9rsc/gravito_crystall_icon.png?rlkey=qzmf4edoq17e52vivwsczjaq9&dl=1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% модов установлено"
	#The buttons to display on Discord 

	[[init.buttons]]
		label = "Создано Saudate Studio"
		url = "https://saudade-studio.ru/"

	[[init.buttons]]
		label = "Дополнено LateTeam"
		url = "https://discord.gg/hcMGhSTYdY"


[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% перевернул сознание"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://www.dropbox.com/scl/fi/tjpu26x8qecq8fxdj5s0f/_-_-_.png?rlkey=okrdw69upjrdnmd10iune8igq&dl=1"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Майнкрафт Сборка [%mcver%]"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["https://www.dropbox.com/scl/fi/6k2s7bmxmcaveb3i4s07a/iron_gear_icon.png?rlkey=itpf9ylnpwn21yljvr5qmtuvh&dl=1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "Находится в Меню"
	#The buttons to display on Discord 

	[[main_menu.buttons]]
		label = "Создано Saudate Studio"
		url = "https://saudade-studio.ru/"

	[[main_menu.buttons]]
		label = "Дополнено LateTeam"
		url = "https://discord.gg/hcMGhSTYdY"


[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% смотрит сервера"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://www.dropbox.com/scl/fi/tjpu26x8qecq8fxdj5s0f/_-_-_.png?rlkey=okrdw69upjrdnmd10iune8igq&dl=1"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Майнкрафт Сборка [%mcver%]"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["https://www.dropbox.com/scl/fi/uslz7n9fdw20gw33nksgc/note_book.png?rlkey=yudqeblm7ne95ppjlpfmmj570&dl=1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "В поисках вечности"
	#The buttons to display on Discord 

	[[server_list.buttons]]
		label = "Создано Saudate Studio"
		url = "https://saudade-studio.ru/"

	[[server_list.buttons]]
		label = "Дополнено LateTeam"
		url = "https://discord.gg/hcMGhSTYdY"


[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = false
	#The first line of text under the app name
	description = "%player% is looking for a Realm"
	#The second line of text under the app name
	state = "Browsing Realms"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["mclogonew"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 
	buttons = []

[join_game]
	#Enable/Disable the Join Game Event
	enabled = false
	#The first line of text under the app name
	description = "%player% is joining a game"
	#The second line of text under the app name
	state = "Joining Game"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["mclogonew"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 
	buttons = []

[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Обитает  в %world%"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://www.dropbox.com/scl/fi/tjpu26x8qecq8fxdj5s0f/_-_-_.png?rlkey=okrdw69upjrdnmd10iune8igq&dl=1"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Майнкрафт Сборка [%mcver%]"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["https://www.dropbox.com/scl/fi/kmhe9hlkh3sq1f7e4gv6r/wandering_icon.png?rlkey=19ow0bthk5n46auoisxgu9hhs&dl=1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[single_player.buttons]]
		label = "Создано Saudate Studio"
		url = "https://saudade-studio.ru/"

	[[single_player.buttons]]
		label = "Дополнено LateTeam"
		url = "https://discord.gg/hcMGhSTYdY"


[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Покоряет %servername%"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://www.dropbox.com/scl/fi/tjpu26x8qecq8fxdj5s0f/_-_-_.png?rlkey=okrdw69upjrdnmd10iune8igq&dl=1"]
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["https://www.dropbox.com/scl/fi/kmhe9hlkh3sq1f7e4gv6r/wandering_icon.png?rlkey=19ow0bthk5n46auoisxgu9hhs&dl=1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[multi_player.buttons]]
		label = "Создано Saudate Studio"
		url = "https://saudade-studio.ru/"

	[[multi_player.buttons]]
		label = "Дополнено LateTeam"
		url = "https://discord.gg/hcMGhSTYdY"


[realms]
	#Enable/Disable the Realms Game Event
	enabled = false
	#The first line of text under the app name
	description = "Playing on %realmname%"
	#The second line of text under the app name
	state = "Playing on a Realm"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["mclogonew"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	#The buttons to display on Discord 
	buttons = []

[generic]
	#The first line of text under the app name
	description = "%player% путешествует"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://www.dropbox.com/scl/fi/tjpu26x8qecq8fxdj5s0f/_-_-_.png?rlkey=okrdw69upjrdnmd10iune8igq&dl=1"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Майнкрафт Сборка [%mcver%]"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["https://www.dropbox.com/scl/fi/3yytv5pmonpds8sba9rsc/gravito_crystall_icon.png?rlkey=qzmf4edoq17e52vivwsczjaq9&dl=1"]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[generic.buttons]]
		label = "Создано Saudate Studio"
		url = "https://saudade-studio.ru/"

	[[generic.buttons]]
		label = "Дополнено LateTeam"
		url = "https://discord.gg/hcMGhSTYdY"


[custom]
	#Must these variables be parsed along with other variables
	enabled = false
	#Your custom variables to add
	variables = []

[dimension_overrides]
	enabled = true

	[[dimension_overrides.dimensions]]
		name = "wasteland:wasteland"
		description = "%player% бредёт в Пустоши"
		state = ""
		largeImageKey = ["https://www.dropbox.com/scl/fi/tjpu26x8qecq8fxdj5s0f/_-_-_.png?rlkey=okrdw69upjrdnmd10iune8igq&dl=1"]
		largeImageText = "Майнкрафт Сборка [%mcver%]"
		smallImageKey = ["https://www.dropbox.com/scl/fi/9slru1afnxcx7yc3w9jr4/wasteland.png?rlkey=g390ul1t3njoi8ay5n18mtj9b&dl=1"]
		smallImageText = ""

		[[dimension_overrides.dimensions.buttons]]
			label = "Создано Saudate Studio"
			url = "https://saudade-studio.ru/"

		[[dimension_overrides.dimensions.buttons]]
			label = "Дополнено LateTeam"
			url = "https://discord.gg/hcMGhSTYdY"


	[[dimension_overrides.dimensions]]
		name = "ecod:the_depths"
		description = "%player% ходит вверх ногами"
		state = ""
		largeImageKey = ["https://www.dropbox.com/scl/fi/tjpu26x8qecq8fxdj5s0f/_-_-_.png?rlkey=okrdw69upjrdnmd10iune8igq&dl=1"]
		largeImageText = "Майнкрафт Сборка [%mcver%]"
		smallImageKey = ["https://www.dropbox.com/scl/fi/02yrh6u3875q7p4lxlh7g/magic_bottle_icon.png?rlkey=pkwi58it6f9kx8r6jnqio1p19&dl=1"]
		smallImageText = ""

		[[dimension_overrides.dimensions.buttons]]
			label = "Создано Saudate Studio"
			url = "https://saudade-studio.ru/"

		[[dimension_overrides.dimensions.buttons]]
			label = "Дополнено LateTeam"
			url = "https://discord.gg/hcMGhSTYdY"


	[[dimension_overrides.dimensions]]
		name = "cyao_coreworld:core_dimension_one"
		description = "%player% опустился к Ядру"
		state = ""
		largeImageKey = ["https://www.dropbox.com/scl/fi/tjpu26x8qecq8fxdj5s0f/_-_-_.png?rlkey=okrdw69upjrdnmd10iune8igq&dl=1"]
		largeImageText = "Майнкрафт Сборка [%mcver%]"
		smallImageKey = ["https://www.dropbox.com/scl/fi/i6c54qkzeryk9q3jm60at/core_icon.png?rlkey=81bteiyi8s3t28b76f5wh2o1y&dl=1"]
		smallImageText = ""

		[[dimension_overrides.dimensions.buttons]]
			label = "Создано Saudate Studio"
			url = "https://saudade-studio.ru/"

		[[dimension_overrides.dimensions.buttons]]
			label = "Дополнено LateTeam"
			url = "https://discord.gg/hcMGhSTYdY"


	[[dimension_overrides.dimensions]]
		name = "cyao_coreworld:inner_place"
		description = "%player% встретился с прошлым"
		state = ""
		largeImageKey = ["https://www.dropbox.com/scl/fi/tjpu26x8qecq8fxdj5s0f/_-_-_.png?rlkey=okrdw69upjrdnmd10iune8igq&dl=1"]
		largeImageText = "Майнкрафт Сборка [%mcver%]"
		smallImageKey = ["https://www.dropbox.com/scl/fi/i6c54qkzeryk9q3jm60at/core_icon.png?rlkey=81bteiyi8s3t28b76f5wh2o1y&dl=1"]
		smallImageText = ""

		[[dimension_overrides.dimensions.buttons]]
			label = "Создано Saudate Studio"
			url = "https://saudade-studio.ru/"

		[[dimension_overrides.dimensions.buttons]]
			label = "Дополнено LateTeam"
			url = "https://discord.gg/hcMGhSTYdY"


	[[dimension_overrides.dimensions]]
		name = "cyao_coreworld:core_dimension_final"
		description = "%player% постигает мироздание"
		state = ""
		largeImageKey = ["https://www.dropbox.com/scl/fi/tjpu26x8qecq8fxdj5s0f/_-_-_.png?rlkey=okrdw69upjrdnmd10iune8igq&dl=1"]
		largeImageText = "Майнкрафт Сборка [%mcver%]"
		smallImageKey = ["https://www.dropbox.com/scl/fi/i6c54qkzeryk9q3jm60at/core_icon.png?rlkey=81bteiyi8s3t28b76f5wh2o1y&dl=1"]
		smallImageText = ""

		[[dimension_overrides.dimensions.buttons]]
			label = "Создано Saudate Studio"
			url = "https://saudade-studio.ru/"

		[[dimension_overrides.dimensions.buttons]]
			label = "Дополнено LateTeam"
			url = "https://discord.gg/hcMGhSTYdY"

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "cyao_structures:primary_databank"
		#The first line of text under the app name
		description = "%player% изучает Врата"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = ["https://www.dropbox.com/scl/fi/tjpu26x8qecq8fxdj5s0f/_-_-_.png?rlkey=okrdw69upjrdnmd10iune8igq&dl=1"]
		#The text that gets displayed when the large image is hovered
		largeImageText = "Майнкрафт Сборка [%mcver%]"
		#The Asset ID of the image to display as the small image
		smallImageKey = ["https://www.dropbox.com/scl/fi/3x5dqq4tuh6c0agoz5su8/orb6.png?rlkey=v835t0j8i8lvqer1trk9a17gh&dl=1"]
		#The text that gets displayed when the small image is hovered
		smallImageText = ""

		#The buttons to display on Discord
		[[dimension_overrides.dimensions.buttons]]
			label = "Создано Saudade Studio"
			url = "https://saudade-studio.ru/"

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "cyao_structures:secondary_databank"
		#The first line of text under the app name
		description = "%player% видит сны"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = ["https://www.dropbox.com/scl/fi/tjpu26x8qecq8fxdj5s0f/_-_-_.png?rlkey=okrdw69upjrdnmd10iune8igq&dl=1"]
		#The text that gets displayed when the large image is hovered
		largeImageText = "Майнкрафт Сборка [%mcver%]"
		#The Asset ID of the image to display as the small image
		smallImageKey = ["https://www.dropbox.com/scl/fi/pvivrtlv39wpvvjsjrlpi/orb1.png?rlkey=8r81wfj9ogg9syy1qlt9f6bw7&dl=1"]
		#The text that gets displayed when the small image is hovered
		smallImageText = ""

		#The buttons to display on Discord
		[[dimension_overrides.dimensions.buttons]]
			label = "Создано Saudade Studio"
			url = "https://saudade-studio.ru/"


