
[THEMES]
	#Allowed Values: SHADOW, PINK, DESIDERIUM, CUSTOM
	"Shop Theme" = "DESIDERIUM"

	[THEMES.THEMES_CUSTOM]
		#Colors Settings
		background = "#5555FF"
		shadow = "#5555FF"
		react = "#5555FF"
		stoke = "#5555FF"

